title: RH3D design
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
color_scheme: dark_green

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/RH3D.jpeg"

url: https://rh3d.github.io/E3NG_docs

aux_links:
  Printables: https://www.printables.com/en/@radkoko
  Discord: https://discord.com/invite/Zkvu6uu2AR
  Ko-Fi: https://ko-fi.com/rh3dcz
